---
title: "Handwritten MCMC 2"
output:
  pdf_document: default
  html_notebook: default
geometry: "left=3cm,top=3cm,right=3cm"
fontsize: 11pt
---

```{r inits}
#knitr::opts_chunk$set(eval = FALSE)
```


```{r load packages}
pkgs = c("compiler", "profvis", "igraph","microbenchmark", "Rcpp")
inst = lapply(pkgs, library, character.only = TRUE)
```


```{R rcpp, eval = FALSE}
#rcpp functions used to speed up parts of the likelihood computation

#cpp version of an unnormalized dpois where log = TRUE
#pre: two numeric vectors of the same length
#post: unnormalized loglikelhood

cppFunction("double mypois(NumericVector data, NumericVector lambdas) {
  int n = data.size();
  NumericVector plik(n);
  plik = -lambdas + data*log(lambdas);

  double tlik = 0;

  for(int i = 0; i < n; ++i){
    tlik += plik[i];
  }

  return tlik;
  }")

cppFunction("NumericVector diff(NumericVector x){
   return diff(x);
}")

cppFunction("NumericVector sort(NumericVector x) {
   NumericVector y = clone(x);
   std::sort(y.begin(), y.end());
   return y;
}")

```


```{r mypoisR}
mypois <- function(data, lambdas) {
  sum(-lambdas + data*log(lambdas))
}
```


# graph gen 1
```{r graph simulation}
#this code block simulates data used in the MCMC


#-----------graph initialization

# edgelist for handrawn graph
el = matrix(c(1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 2, 7, 2, 8, 7, 8, 6, 9, 9, 10),
            byrow = TRUE,
            ncol = 2)

# g_city = graph_from_edgelist(el, directed = FALSE)

# ER random graph
g_city = sample_gnp(15, 0.12)
plot(g_city)

adjlist = as_adj_list(g_city, mode = 'all')

#unclass from igraph for later use
unclass_adjlist <- function(adjlist) {
  adjlist <- unclass(adjlist)
  for (i in 1:length(adjlist)) {
    adjlist[[i]] = unclass(adjlist[[i]])
  }
  return(adjlist)
}

adjlist <- unclass_adjlist(adjlist)


#---simulate endemic component based on paper's values----#
#-----------NOTE: need to divide the rate since each city gets a chance

#initial paramaters
N = 199 #total epochs/time steps
init = 10   #Z_0 value is the initial number of people infected

#------- setting endemic parameters
gamma  <- c(log(10), 0.5, 1.5)/2
rho <- 2*pi/52 

# generates values
t = 1:N
INDEP <- as.matrix(data.frame(x0 = 1, x1 = sin(rho*t), x2 = cos(rho*t*1.5)))
nu_t <- as.matrix(INDEP) %*% gamma

ende_lambda = rep(0, N)
ende_lambda = exp(nu_t)

#-----setting epidemic lambda values
K <- 2 #changepoints
theta  <- c(39, 49) #location of changepoints
migration <- 0.31

#lambda values
lambda <- c(0.5, 1.5, 0.5)/2
#lambda vector 
epi_lambda = rep(lambda, diff(c(0, theta, N)))



#list of actual parameter values; useful for testing



#-----------------counts matrix ------
#separate counts from the ende and epi components
ende_c = matrix(0, nrow = gorder(g_city), ncol = N)
epi_c = matrix(0, nrow = gorder(g_city), ncol = N)

counts = matrix(0, nrow = gorder(g_city), ncol = N)
counts[ ,1] = init


 
#get list of all adjacent vertices
adj = as_adj_list(g_city)

#-----------compute data-----

for (i in 1:(N - 1)) {
  #all rows/cities get same value from the ende
  ende_c[, i] = rpois(gorder(g_city), ende_lambda[i])
  
  for (j in 1:gorder(g_city)) {
    counts_j = sum(counts[adj[[j]], i])*migration #sum all adjacent counts
    counts_j = counts_j + counts[j, i] #add self count
    epi_c[j, i] = rpois(1, epi_lambda[i] * counts_j) #generate new counts
    counts[j , i + 1] = ende_c[j, i] + epi_c[j, i] #append new counts
  }
}

#---plots----
plot(colSums(counts), type = 'l')
lines(colSums(ende_c), col = 'blue', type = 'l')
lines(colSums(epi_c), col = 'red', type = 'l')
title(main = "all cities sum")

plot(counts[1, ], type = 'l', col = 'forestgreen')
lines(ende_c[1, ], type = 'l', col = 'blue')
lines(epi_c[1, ], type = 'l', col = 'red')
title(main = 'city 1')

plot(counts[3, ], type = 'l', col = 'forestgreen')
lines(ende_c[3, ], type = 'l', col = 'blue')
lines(epi_c[3, ], type = 'l', col = 'red')
title(main = 'city 10')

plot(counts[9, ], type = 'l', col = 'forestgreen')
lines(ende_c[9, ], type = 'l', col = 'blue')
lines(epi_c[9, ], type = 'l', col = 'red')
title(main = 'city 10')

plot(g_city)
plot(ende_c[1, ], type = "l", col = "red")
lines(ende_c[2, ], type = "l", col = "forestgreen")
lines(ende_c[3, ], type = 'l', col = "blue")
lines(ende_c[4, ], type = 'l', col = "black")

plot(g_city)
par(mfrow = c(1,2))
plot(counts[10, 30:50], type = "l", col = "red")
lines(counts[12, 30:50], type = "l", col = "forestgreen")
plot(counts[15, 30:50], type = 'l', col = "blue")
lines(counts[11, 30:50], type = 'l', col = "black")
par(mfrow = c(1,2))
plot(counts[10, 30:50], type = "l", col = "red")
lines(counts[11, 30:50], type = "l", col = "forestgreen")
plot(counts[12, 30:50], type = 'l', col = "blue")
lines(counts[15, 30:50], type = 'l', col = "black")


actual <- list(
  K = K,
  theta = theta,
  lambda = lambda,
  LL = -Inf,
  gamma = gamma,
  INDEP = INDEP,
  graph = g_city,
  adj = adjlist,
  counts = counts,
  migration = migration
)
```

# PRIOR

```{r compute_prior}
#' computes the prior of the parameters
#'
#' @param input a list containing the parameters
#' @return the log prior probability of the parameters
compute_prior <- function(input){
  K = input$K
  theta = input$theta
  lambda = input$lambda
  gamma = input$gamma
  
  adj = input$adj
  count = input$ec[["count"]]
  
  prior_star <- 0
    -log(choose(N, K)) +
    sum(dgamma(lambda, 1, 1, log = TRUE)) +
    sum(dnorm(gamma, 0, 3, log = TRUE)) +
    dpois(K, 2, log = TRUE)
  #-log( choose( choose(length(adj), 2), count))
     
  return(prior_star)
}
```

# compute_like
```{r graph likelihood}



compute_like <- function(input) {
  K = input$K
  theta = input$theta
  lambda = input$lambda
  gamma = input$gamma
  INDEP = input$INDEP
  LL = input$LL
  adj = input$adj
  counts = input$counts
  migration = input$migration
  
  
  #replicate lambda values to the correct length according to the changepoints
  if (K == 0) {
    vepi_star <- rep(lambda, N)
  } else {
    vepi_star <- rep(lambda, diff(c(0, theta, N)))
  }
  
  
  #generate the infection counts matrix according to which vertices/cities are
  #adjacent
  ord = length(adj)  #number of vertices in the graph
  inf_counts = matrix(0, nrow = ord, ncol = N)
  
  for (i in 1:ord) {
    #inf_counts[i, ] = colSums(counts[adj[[i]], , drop = FALSE])*migration + counts[i, ]
    inf_counts[i, ] = .colSums(counts[adj[[i]], , drop = FALSE], length(adj[[i]]), N)*migration + counts[i, ]
  }
  
  # ------- endemic and epidemic parameter matrices ----
  nu <- exp(INDEP %*% gamma)         #generate nu parameter for endemic
  #creates matrix of repeated rows
  mat_ende_lambda <- matrix(rep(nu, ord), nrow = ord, byrow = TRUE)
  
  #creates matrix of lambdas from estimated lambda row
  mat_lambdas <-
    matrix(rep(vepi_star, ord), nrow = ord, byrow = TRUE)
  
  #compute the log-likelihood
  #data is for 2:N, first column is an initial value
  log_lik <-
    mypois(counts[, 2:N], 
            inf_counts[, 1:(N - 1)] * mat_lambdas[, 1:(N - 1)] 
            + mat_ende_lambda[, 1:(N - 1)])
  
  return(log_lik)
}

#-------for prior testing--------

# compute_like <- function(input){
# 
#   0
# }
```

# base operators

## migration

```{r}
change_migration <- function(input) {
  LL <- input$LL
  migration <- input$migration
  
  #propose new state from normal
  migration_star <- migration + runif(1, -0.01, 0.01)
  
  if (migration_star > 1 || migration_star < 0){
    return(input)
  }
  
  #repackage list
  input_star <- input
  input_star$migration <- migration_star
  
  LL_star <- compute_like(input_star) #compute log likelihood
  prior_star <-  compute_prior(input_star) #compute LOG prior
  post_star <- LL_star + prior_star #new log posterior
  
  U = runif(1)
  
  if (log(U) < post_star - LL) {
    input_star$LL <- post_star
    return(input_star)
  } else {
    return(input)
  }
  
}
```


## other

```{r operators}
#' Proposes a new gamma parameter vector from a random normal
#'  Metropolis Random Walk (MRW)
#' @param input a list containing the current parameter state
#' @return a list of either the newly proposed state (input_star) or the current
#'  Metropolis Random Walk (MRW)

change_gamma <- function(input) {
  LL <- input$LL
  gamma <- input$gamma
  
  #propose new state from normal
  gamma_star <- gamma + rnorm(3, 0, 0.01)
  
  #repackage list
  input_star <- input
  input_star$gamma <- gamma_star
  
  LL_star <- compute_like(input_star) #compute log likelihood
  prior_star <-  compute_prior(input_star) #compute LOG prior
  post_star <- LL_star + prior_star #new log posterior
  
  U = runif(1)
  
  if (log(U) < post_star - LL) {
    input_star$LL <- post_star
    return(input_star)
  } else {
    return(input)
  }
  
}


#' Proposes removing a changepoint. Uses a Reversible Jump MCMC (RJMCMC) as seen
#'  in Green 1995
#' @param input a list containing the current parameter state
#' @return a list of either the newly proposed state (input_star) or the current
#'  state (input)

death_theta <- function(input) {
  K = input$K
  theta = input$theta
  lambda = input$lambda
  LL = input$LL
  
  #if K = 0 (no change points) then automatically reject this proposal
  if (K == 0) {
    return(input)
  }
  
  #randomly sample from the current list of changepoints
  m <- ceiling(runif(1,0,length(theta)))
  theta_star <- theta[c(-m)]  # remove that from the list
  
  #adjusting lambda values due to removal of changepoint
  #find lambda values that were adjacent to changepoint m
  lambda1 <- lambda[m]     
  lambda2 <- lambda[m + 1]
  
  #adds endpoints to the vector of theta values
  temp_theta = c(0, theta, N)
  j = m + 1
  
  #crate new value as a geometric weighted sum of the previous two lambda values
  lambda0 <- lambda1^((temp_theta[j] - temp_theta[j - 1])/(temp_theta[j + 1] - temp_theta[j - 1])) *
    lambda2^((temp_theta[j + 1] - temp_theta[j])/(temp_theta[j + 1] - temp_theta[j - 1]))
  
  #create new lambda proposal vector
  lambda_star <- lambda
  lambda_star[m] <- lambda0 #insert the lambda value into the correct location
  lambda_star <- lambda_star[-c(m + 1)] #delete the extra value
  
  #repackage values into input_star
  input_star <- input
  input_star$lambda <- lambda_star
  input_star$theta <- theta_star
  input_star$K <- K - 1
  
  #compute log likelihood
  LL_star <- compute_like(input_star)
  #compule log prior
  prior_star <-  compute_prior(input_star)
  post_star <- LL_star + prior_star #new log posterior
  
  #hastings ratio
  #tk double check this
  hastings <- log(K) - log(N - (K - 1))
  
  #value preserving jacobian for RJMCMC
  log_jacobian <- -2*log(lambda1 + lambda2) + log(lambda0)
  #final log acceptance
  alpha <- post_star  - LL + log_jacobian + hastings
  
  if (alpha > log(runif(1))) {
    input_star$LL <- post_star
    return(input_star)
  }  else {
    return(input)
  }
} 


#' Proposes adding a changepoint. Uses a Reversible Jump MCMC (RJMCMC) as seen
#'  in Green 1995
#' @param input a list containing the current parameter state
#' @return a list of either the newly proposed state (input_star) or the current
#'  state (input)

birth_theta <- function(input) {
  K = input$K
  theta = input$theta
  lambda = input$lambda

  LL = input$LL

  #if K = N, the max number of time steps then automatically reject this propos
  if (K == N) {
    return(input)
  }
  

  #theta_m <- sample(setdiff(1:N, theta), 1)  # birth
  
  #randomly sample from all possible time steps
  theta_m <- ceiling(runif(1, 0, N))
  #resample if the time step is already in the changepoint list
  while (theta_m %in% theta) {
    theta_m <- ceiling(runif(1, 0, N))
  }
  
  #create a theta vector with the newly proposed changepoint
  theta_star <- sort(c(theta, theta_m))
  #determine the location of the changepoint in the vector
  m <- which(theta_star == theta_m)      
  
  #add endpoints
  temp_theta_star = c(0, theta_star, N)
  
  #---update lambda vectors; RJMCMC
  u <- runif(1)
  j = m + 1 #indexing help
  #take original lambda value and split is as a geoemtric average
  lambda0 <- lambda[m]
  lambda1 <- lambda0*(u/(1 - u))^((temp_theta_star[j] - temp_theta_star[j - 1])/(temp_theta_star[j + 1] - temp_theta_star[j - 1]))
  lambda2 <- lambda0*((1 - u)/u)^((temp_theta_star[j + 1] - temp_theta_star[j])/(temp_theta_star[j + 1] - temp_theta_star[j - 1]))
  
  #edge case when there is no changepoint
  if (K == 0){
    lambda0 <- lambda[1]
    lambda1 <- lambda0*(u/(1 - u))^((temp_theta_star[j] - temp_theta_star[j - 1])/(temp_theta_star[j + 1] - temp_theta_star[j - 1]))
    lambda2 <- lambda0*((1 - u)/u)^((temp_theta_star[j + 1] - temp_theta_star[j])/(temp_theta_star[j + 1] - temp_theta_star[j - 1]))
  }
  
  
  # updating the lambda vector according to the location of the changepoint
  if (m == 1) {
    lambda_star <- c(lambda1, lambda2, lambda[-1])
  }
  else if (m == length(theta_star)) {
    lambda_star <- c(lambda[1:K], lambda1, lambda2)
  }
  else {
    lambda_star <- c(lambda[1:(m - 1)], lambda1, lambda2, lambda[(m + 1):(K + 1)])
  }
  
  #repackage the new proposed state
  input_star <- input
  input_star$lambda <- lambda_star
  input_star$theta <- theta_star
  input_star$K <- K + 1
  
  LL_star <- compute_like(input_star)
  prior_star <-  compute_prior(input_star)
  post_star <- LL_star + prior_star #new log posterior
  
  
  #hastings ratio
  hastings <- -log(K + 1) + log(N - K)
  log_jacobian <- 2*log(lambda1 + lambda2) - log(lambda0)
  
  alpha <- post_star  - LL + log_jacobian + hastings
  
  if (alpha > log(runif(1))) {
    input_star$LL <- post_star
    return(input_star)
  }
  else {
    return(input)
  }
}


#' Moves a changepoint. Moves it anywhere between the previous changepoint and
#'  the next changepoint
#' 
#' @param input a list containing the current parameter state
#' @return a list of either the newly proposed state (input_star) or the current
#'  state (input)

change_theta <- function(input) {
  K = input$K
  theta = input$theta
  LL = input$LL
  
  #edge case; K = 0, nothing to move; K = N no where to move
  if (K == 0 || K == N) {
    return(input)
  }
  
  #location of the selected changepoint in the temp_theta vector
  j <- sample(1:K, size = 1) + 1 
  #j <- ceiling(runif(1,1,K+1))
  
  temp_theta <- c(0, theta, N + 1)
  
  #if there's no space to move the changepoint
  if (temp_theta[j + 1] - temp_theta[j - 1] < 2) {
    return(input)
  }
  
  #newly proposed location
  s_star <-
    ceiling(runif(1, temp_theta[j - 1], temp_theta[j + 1] - 1))
  #s_star <- temp_theta[j] + sample(c(-1,1),1)
  
  #proposed theta vector
  theta_star <- theta
  theta_star[j - 1] <- s_star
  
  input_star <- input
  input_star$theta <- theta_star
  
  LL_star <-
    compute_like(input_star) 
  prior_star <-  compute_prior(input_star)
  post_star <- LL_star + prior_star 
  
  U <- runif(1)
  
  if (log(U) < post_star - LL) {
    input_star$LL <- post_star
    return(input_star)
  } else {
    return(input)
  }
}

#' Proposes a new lambda parameter vector from a random normal
#'  Metropolis Random Walk (MRW)
#' @param input a list containing the current parameter state
#' @return a list of either the newly proposed state (input_star) or the current
#'  (input)

change_lambda <- function(input, componentwise = FALSE) {
  K = input$K
  theta = input$theta
  lambda = input$lambda
  gamma = input$gamma
  INDEP = input$INDEP
  LL = input$LL
  graph = input$graph
  adj = input$adj
  
  # #component wise
  # j <- sample(1:(K + 1), size = 1)
  # lambda_star[j] <- lambda_star[j] + rnorm(1,0,0.01)
  
  lambda_star <- lambda
  lambda_star <- lambda_star + rnorm(K + 1, 0, 0.0025)
  
  input_star <- input
  input_star$lambda <- lambda_star
  
  LL_star <- compute_like(input_star)
  prior_star <-   compute_prior(input_star) 
  post_star <- LL_star + prior_star #new log posterior
  
  #edge case
  if (post_star == -Inf && LL == -Inf) {
    return(input)
  }
  
  U = runif(1)
  
  if (log(U) < post_star - LL) {
    input_star$LL <- post_star
    return(input_star)
  } else {
    return(input)
  }
}


```


# graph operators

```{r graph_ops}

add_edge_op <- function(input){
    K = input$K
  theta = input$theta
  lambda = input$lambda
  gamma = input$gamma
  INDEP = input$INDEP
  LL = input$LL
  
  ec_star = input$ec
  adj = input$adj
  ord = length(adj)
  
  counts = sapply(adj, length)
  
  
  v1s = sample(1:ord, 2)
  
  if (v1s[1] %in% adj[[v1s[2]]]){
    input$graph = 0
    return(input)
  }
 
  adj_star <- add_edge(adj, c(v1s[1], v1s[2]))

  input_star <- input
  input_star$adj <- adj_star
 
  
  LL_star <- compute_like(input_star)
  prior_star <- compute_prior(input_star)
  post_star <- LL_star + prior_star #new log posterior

  U = runif(1)
  
  if (log(U) < post_star - LL) {
    input_star$graph = 1
    input_star$LL <- post_star
    return(input_star)
    
  } else {
    input$graph <- 0
    return(input)
  }
  
}

del_edge_op <- function(input){
  K = input$K
  theta = input$theta
  lambda = input$lambda
  gamma = input$gamma
  INDEP = input$INDEP
  LL = input$LL
  
  ec_star = input$ec
  adj = input$adj
  ord = length(adj)
  
  counts = sapply(adj, length)
  
  
  v1s = sample(1:ord, 1, prob = counts)
  
  v11 <- v1s[1]
  
  if (length(adj[[v11]]) == 1) {
    v12 = adj[[v11]]
  } else {
    v12 = sample(adj[[v11]], 1, replace = TRUE)
  }
  
 
  adj_star <- remove_edge(adj, c(v11, v12))

  input_star <- input
  input_star$adj <- adj_star
 
  
  LL_star <- compute_like(input_star)
  prior_star <- compute_prior(input_star)
  post_star <- LL_star + prior_star #new log posterior

  U = runif(1)
  
  if (log(U) < post_star - LL) {
    input_star$graph = 1
    input_star$LL <- post_star
    return(input_star)
    
  } else {
    input$graph <- 0
    return(input)
  }
  
}


rewire <- function (input){
  #randomly pick edge
  #vertex weighted
  #random sample
  #v11:..... v12
  #v21: ..... if not in then move it
  #
  K = input$K
  theta = input$theta
  lambda = input$lambda
  gamma = input$gamma
  INDEP = input$INDEP
  LL = input$LL
  
  ec_star = input$ec
  adj = input$adj
  ord = length(adj)
  
  counts = sapply(adj, length)
  
  i = 0
  repeat{
  i = i + 1
  if (i == 50) {
    input$graph = -1
    return(input)
  }
  v1s = sample(1:ord, 2, prob = counts)
  v11 <- v1s[1]
  v21 <- sample(1:ord, 1)
  
  if (length(adj[[v11]]) == 1) {
    v12 = adj[[v11]]
  } else {
    v12 = sample(adj[[v11]], 1, replace = TRUE)
  }
  
  if (v12 %in% adj[[v21]]) {
    next
  }
  }

  adj_star <- remove_edge(adj, c(v11, v12))
  adj_star <- add_edge(adj_star, c(v21, v12))

  input_star <- input
  input_star$adj <- adj_star
 
  
  LL_star <- compute_like(input_star)
  prior_star <- compute_prior(input_star)
  post_star <- LL_star + prior_star #new log posterior

  U = runif(1)
  
  if (log(U) < post_star - LL) {
    input_star$graph = 1
    input_star$LL <- post_star
    return(input_star)
    
  } else {
    input$graph <- 0
    return(input)
  }
  

  
  
}


#-----------------makes graph props-------------------
degree_preserving <- function(input) {
  K = input$K
  theta = input$theta
  lambda = input$lambda
  gamma = input$gamma
  INDEP = input$INDEP
  LL = input$LL
  
  ec_star = input$ec
  adj = input$adj
  ord = length(adj)
  
  counts = sapply(adj, length)
  
  i = 0
  repeat {
  i = i + 1
  if (i == 20) {
    input$graph <- -1
    return(input)
  }
  v1s = sample(1:ord, 2, prob = counts)
  v11 <- v1s[1]
  v21 <- v1s[2]
  
  if (length(adj[[v11]]) == 1) {
    v12 = adj[[v11]]
  } else {
    v12 = sample(adj[[v11]], 1, replace = TRUE)
  }
  

   
  
    
    if (v21 %in% c(v11, v12, adj[[v12]])) {
      next
    }
    
    
    if (length(adj[[v21]]) == 1) {
      v22 = adj[[v21]]
    } else {
      v22 = sample(adj[[v21]], 1, replace = TRUE)
    }
    
    if (v22 %in% c(v11, v12, adj[[v11]])) {
      next
    } else {
      break
    }
    
    
  }
  
  
  
  
  


  adj_star <- remove_edge(adj, c(v11, v12))
  adj_star <- remove_edge(adj_star, c(v21, v22))
  
  adj_star <- add_edge(adj_star, c(v11, v22))
  adj_star <- add_edge(adj_star, c(v21, v12))
  
  input_star <- input
  input_star$adj <- adj_star
 

  
  LL_star <- compute_like(input_star)
  prior_star <- compute_prior(input_star)
  post_star <- LL_star + prior_star #new log posterior

  U = runif(1)
  
  if (log(U) < post_star - LL) {
    input_star$graph = 1
    input_star$LL <- post_star
    return(input_star)
    
  } else {
    input$graph <- 0
    return(input)
  }
  

  
}



#' Randomly selects a possible edge and flips its current state
#'
#' @param input 
#'
#' @return
#' @export
#'
#' @examples

#-----------flip edge operator



flip_edge <- function(input, mig = FALSE) {
  K = input$K
  theta = input$theta
  lambda = input$lambda
  gamma = input$gamma
  INDEP = input$INDEP
  LL = input$LL
  migration = input$migration
  
  ec_star = input$ec 
  adj = input$adj
  ord = length(adj)
  
  adj_star <- adj
  
  if (runif(1) < 1) {
    stepl = 1
  } else {
    stepl = 3
  }
  
  for (i in 1:stepl) {
    ep = sample(1:ord, 2, replace = FALSE)
    
    if (ep[1] %in% adj_star[[ep[2]]]) {

      adj_star <- remove_edge(adj_star, ep)
      
      if (mig) {migration_star <- migration + runif(1, 0, 0.05)}
      
      ec_star = update_edge_c(ec_star, ep[1], ep[2], "del")
      ec_star$count = ec_star$count - 1
      
    } else {

      adj_star <- add_edge(adj_star, ep)
      
      if (mig) { migration_star <- migration - runif(1, 0.000, 0.05)}
     
      
      ec_star = update_edge_c(ec_star, ep[1], ep[2], "add")
      ec_star$count = ec_star$count + 1
    }
  }
  
  input_star <- input
  input_star$adj <- adj_star
  input_star$ec <- ec_star
  input_star$migration <- migration_star
  
  LL_star <- compute_like(input_star)
  prior_star <- compute_prior(input_star)
  post_star <- LL_star + prior_star #new log posterior
  
  
  U = runif(1)
  
  if (log(U) < post_star - LL) {
    input_star$graph = 1
    input_star$LL <- post_star
    return(input_star)
    
  } else {
    input$graph <- 0
    return(input)
  }
  
  
  
}

#------------helpers------
#
#

remove_edge <- function(adj_star, ep) {
  m = which(adj_star[[ep[2]]] == ep[1])
  adj_star[[ep[2]]] = adj_star[[ep[2]]][-m]
  
  m = which(adj_star[[ep[1]]] == ep[2])
  adj_star[[ep[1]]] = adj_star[[ep[1]]][-m]
  
  return(adj_star)
}

add_edge <- function(adj_star, ep) {
  adj_star[[ep[2]]] = sort(c(adj_star[[ep[2]]], ep[1]))
  adj_star[[ep[1]]] = sort(c(adj_star[[ep[1]]], ep[2]))
  
  return(adj_star)
}
      



update_edge_c <- function(elist, v1, v2, update_t) {
  n_v1 <- as.character(v1)
  n_v2 <- as.character(v2)
  
  decrement_edge_c <- function(elist, n_v1, n_v2) {
    if (elist[[n_v1]] == 1) {
      elist[n_v1] <- NULL
    } else {
      elist[[n_v1]] = elist[[n_v1]] - 1
    }
    
    if (elist[[n_v2]] == 1) {
      elist[n_v2] <- NULL
    } else {
      elist[[n_v2]] = elist[[n_v2]] - 1
    }
    return(elist)
    
  }
  
  increment_edge_c <- function(elist, n_v1, n_v2) {
    if (is.null(elist[[n_v1]])) {
      elist[[n_v1]] <- 1
    } else {
      elist[[n_v1]] = elist[[n_v1]] + 1
    }
    
    if (is.null(elist[[n_v2]])) {
      elist[[n_v2]] <- 1
    } else {
      elist[[n_v2]] = elist[[n_v2]] + 1
    }
    return(elist)
    
  }
  
  
  if (update_t == "del") {
    elist = decrement_edge_c(elist, n_v1, n_v2)
  } else if (update_t == "add") {
    elist = increment_edge_c(elist, n_v1, n_v2)
  }
  
  return(elist)
}

```


# SAMPLERS

## migration

```{r}
update_param_mig <- function(input) {

  U = runif(1)
  if (U < 0) {
  output <- flip_edge(input)
  } else {
    output <- change_migration(input)
  }
  
  return(output)
}

update_param5 <- function(input){
  U = runif(1)
  if (U < 1/2){
    output <- add_edge_op(output)
  } else {
    output <- del_edge_op(output)
  }
}

```


## other

```{r update_param}


update_param4 <- function(input) {
  cutoff <- 1 / 6
  
  p = runif(1)
  if (p < cutoff) {
    output <- birth_theta(input)
  } else if (p < 2 * cutoff) {
    output <- change_theta(input)
  } else if (p < 3 * cutoff) {
    output <- change_lambda(input)
  }  else if (p < 4 * cutoff) {
    output <- change_gamma(input)
  } else if (p < 5 * cutoff) {
    output <- degree_preserving(input)
  }
  else  {
    output <- death_theta(input)
  }
  return(output)
  
}

update_param3 <- function(input) {
  U = runif(1)
  if (U < 1/4) {
    output <- flip_edge(input, mig = TRUE)
  
  } else if (U < 2/4) {
    output <- degree_preserving(input)
    
  } else if (U < 3/4) {
    output <- rewire(input)
  } else {
   output <- change_migration(input)
  }
  return(output)
}



update_param5 <- function(input){
  U = runif(1)
  if (U < 1){
    output <- flip_edge(input, mig = TRUE)
  } else {
    output <- change_migration(output)
  }
}
```


# MCMC

```{r MCMC}

ops = c(death_theta,
        birth_theta,
        change_theta,
        change_lambda,
        change_gamma,
        flip_edge,
        rewire,
        degree_preserving,
        change_migration,
        compute_like)
lapply(ops, undebug)


nSim <- 100000
#pre-allocate
res <- list(
  K = numeric(nSim),
  theta = matrix(0, nSim, N),
  lambda = matrix(0, nSim, N + 1),
  gamma = matrix(0, nSim, 3),
  adj = vector(mode = "list", N),
  accept = numeric(nSim),
  edge_count = numeric(nSim),
  migration = numeric(nSim)
)



# output <-
#   list(
#     K = 2,
#     theta = c(39, 49),
#     lambda = lambda,
#     LL = -Inf,
#     gamma = gamma,
#     INDEP = INDEP,
#     adj = full_adjlist,
#     graph = 1,
#     ec = edge_c_list
#   )



init_list <- vector(mode = "list", 15)

edge_c_list = list()
for (i in 1:15){
  edge_c_list[as.character(i)] <- 14
}
edge_c_list$count = choose(15, 2)


#---------initialize edge list ----#
# #create names
# edge_c.names = as.character(1:length(init_list))
# #init vector
# edge_c <- vector(mode = "list", length = length(init_list))
# #name
# names(edge_c) <- edge_c.names


# fill edge list
# for (i in 1:length(init_list)) {
#   num_edge <- length(init_list[[i]])
#   if (num_edge > 0) {
#     edge_c[[i]] <- num_edge
#   } else {
#     edge_c[i] <- NULL
#   }
# }
# --------------------------- #




init_list <- vector(mode = "list", 15)
edge_c_list = list()
edge_c_list$count = 0

 output <-
   list(
     K = 2,
     theta = c(39, 49),
     lambda = lambda,
     LL = -Inf,
     gamma = gamma,
     INDEP = INDEP,
     adj = init_list,
     graph = 1,
     ec = edge_c_list,
     counts = counts,
     migration = 0.9
  )


system.time(for (i in 1:nSim) {
  if (i < 50000) {
  output <-  update_param5(output)
  } else {
    output <-  update_param3(output)
  }
  
  if (i > 50000) {
    #debug(compute_like)
    # debug(flip_edge)
    # debug(rewire)
    # debug(degree_preserving)
  }
  
  k <- output$K
  res$K[i] <- k
  
  if (length(output$theta) == 0) {
    res$theta[i,] <-  0
  } else {
    res$theta[i,] <-   c(output$theta, rep(output$theta[k], N - k))
  }
  
  res$lambda[i,] <-
    c(output$lambda, rep(output$lambda[k + 1], N - k))
  res$gamma[i,] <- output$gamma
  res$accept[i] <- output$graph
  res$count[i] <- output$ec$count
  res$migration[i] <- output$migration
  
  
  if (i %% 5000 == 1 || i == 2) {
    plot(graph.adjlist(output$adj, mode = "all"))
    #debug(death_theta)
    # debug(flip_edge)
    print(output$LL)
    print(output$migration)
  }
  

  
  
})
plot(g_city)
```


# Diagonostics
```{r}

# 
burnin = 20000

par(mfrow = c(1,2))
plot(graph.adjlist(output$adj, mode = "all"))
mean(res$accept[-(1:burnin)] == 1)
hist(res$count[-(1:burnin)])
plot(res$count, type = "l")
plot(res$accept, type = "l")
hist(res$accept[-(1:burnin)], freq = FALSE)
hist(res$count[-(1:burnin)]/45)

plot(res$migration, type = "l")
plot(res$migration[1:length(res$count)], res$count)

```



```{r}
par(mfrow = c(1, 3))
plot(res$gamma[-(1:burnin), 1], type = "l")
plot(res$gamma[-(1:burnin), 2], type = "l")
plot(res$gamma[-(1:burnin), 3], type = "l")
title("Gamma (Endemic) Trace Plots", outer = TRUE)

par(mfrow = c(1, 3))
plot(res$theta[, 1], type = "l")
plot(res$theta[, 2], type = "l")
plot(res$theta[, 3], type = "l")
title("Change Point Trace Plots", outer = TRUE)

par(mfrow = c(2, 2))
plot(res$lambda[-(1:burnin), 1], type = "l")
plot(res$lambda[-(1:burnin), 2], type = "l")
plot(res$lambda[-(1:burnin), 3], type = "l")
plot(res$lambda[-(1:burnin), 4], type = "l")
title("Lambda (epidemic) Trace Plots", outer = TRUE)




par(mfrow = c(2, 3))

plot(colSums(counts), type = "l")
lines(c(177, 177), c(0, 400), col = "red")
hist(res$K[-(1:burnin)], freq = FALSE, breaks = 5)
plot(density(res$lambda[-(1:burnin), 1], bw = 0.01))

plot(density(res$lambda[-(1:burnin), 2], bw = 0.01))

plot(density(res$lambda[-(1:burnin), 3], bw = 0.01))

#(density(res$lambda[-(1:burnin), 4][res$K == 4 ], bw=0.01))

title("Actual, #CP and Lambda densities", outer = TRUE)


par(mfrow = c(2, 3))
plot(density(res$theta[-(1:burnin), 1], bw = 1))
plot(density(res$theta[-(1:burnin), 2], bw = 1))
plot(density(res$theta[-(1:burnin), 3], bw = 1))
plot(density(res$theta[-(1:burnin), 4], bw = 1))
plot(density(res$theta[-(1:burnin), 5], bw = 1))
plot(density(res$theta[-(1:burnin), 6], bw = 1))

par(mfrow = c(1, 3))
plot(density(res$gamma[-(1:burnin), 1], bw = 0.1))
plot(density(res$gamma[-(1:burnin), 2], bw = 0.1))
plot(density(res$gamma[-(1:burnin), 3], bw = 0.1))
title("Theta densities", outer = TRUE)


# K <- 4
#
# theta  <- c(53, 55, 273,280)
#
# lambda <- c(0.7, 1.5, 0.7, 1.1,0.5)
```


```{r }

adjlist = as_adj_list(g_city, mode = 'all')
g = sample_gnp(10, 0.1)
adjlist <- as_adj_list(g)
adjlist <- unclass(adjlist)
for (i in 1:length(adjlist)){
  adjlist[[i]] = unclass(adjlist[[i]])
}

adjlist = vector(mode = "list", 10)

adjlist[[1]] <- c(2, 3, 4, 5, 6)
adjlist[[2]] <- c(1, 7, 8)
adjlist[[3]] <- c(1)
adjlist[[4]] <- c(1)
adjlist[[5]] <- c(1)
adjlist[[6]] <- c(1, 9)
adjlist[[7]] <- c(2, 8)
adjlist[[8]] <- c(2, 7)
adjlist[[9]] <- c(6, 10)
adjlist[[10]] <- c(9)


#---------initialize edge list ----#
#create names
edge_c.names = as.character(1:length(adjlist))
#init vector
edge_c <- vector(mode = "list", length = length(adjlist))
#name
names(edge_c) <- edge_c.names


# fill edge list
for (i in 1:length(adjlist)) {
  num_edge <- length(adjlist[[i]])
  if (num_edge > 0) {
    edge_c[[i]] <- num_edge
  } else {
    edge_c[i] <- NULL
  }
}



delete_edge <- function(input) {
  adj = input$adj
  ord = length(adj)
  
  v1 = sample(1:ord, 1)
  while (length(adj[[v1]]) == 0) {
    v1 = sample(1:ord, 1)
  }
  
  #issues when low number of edges...could just sample forever
  
  m = sample(length(adj[[v1]]), 1)
  
  v2 <- adj[[v1]][m]
  adj[[v1]] <- adj[[v1]][-m]
  
  m = which(adj[[v2]] == v1)
  adj[[v2]] = adj[[v2]][-m]
  
  input$adj <- adj
  return(input)

}



ginput$adj <- adjlist
ginput$ec <- edge_c


par(mfrow = c(5,5))
par(mar = c(0,0,0,0))
plot(graph.adjlist(ginput$adj, mode = "all"))

for (i in 1:24) {
ginput <- flip_edge(ginput)
plot(graph.adjlist(ginput$adj, mode = "all"))
}




 for (i in 1:24) {
 ginput <- delete_edge(ginput)
 plot(graph.adjlist(ginput$adj, mode = "all"))
 }


```


